name: Pipeline CI InstaHealth Expo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    name: Configurar el entorno
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el c贸digo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalar dependencias
        run: npm install

  test:
    name: Ejecutar pruebas
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el c贸digo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm run test

  expo-start-check:
    name: Verificar el inicio de la app con Expo
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el c贸digo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Iniciar Expo en modo web
        run: npm run web

  notify:
    name: Notificar a Slack
    runs-on: ubuntu-latest
    if: failure() # Notificar solo en caso de fallos

    steps:
      - name: Notificar el fallo a Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          custom-payload: |
            {
              "text": " El Pipeline CI fall贸 en el repositorio: ${{ github.repository }} en la rama: ${{ github.ref_name }}.\nDetalles del error: ${{ steps.notify.outputs.failure }}.",
              "attachments": [
                {
                  "color": "danger",
                  "title": "Detalles del Pipeline CI",
                  "fields": [
                    {
                      "title": "Repositorio",
                      "value": "${{ github.repository }}"
                    },
                    {
                      "title": "Rama",
                      "value": "${{ github.ref_name }}"
                    }
                  ]
                }
              ]
            }
